os: osx
language: python
python:
  - "3.6"
sudo: true

install:
  - sudo pip install PyQt5 pyinstaller cffi

script:
  - pyinstaller --windowed browser.spec
  - brew install tree
  - tree dist/WebBrowser.app
  - ./dist/WebBrowser.app/Contents/MacOS/WebBrowser

before_deploy:
  - zip -r build-$TRAVIS_OS_NAME.zip dist/WebBrowser.app

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: $GH_TOKEN
  file:
    - build-$TRAVIS_OS_NAME.zip
  on:
    tags: true
