os: osx
language: generic
services:
  - xvfb
cache:
  pip: true
  directories:
    - $HOME/sip-4.19.13
    - $HOME/PyQt5_gpl-5.11.2
sudo: true


before_install:
  - pip install msgpack gevent enum34
  - cd $( brew --prefix )/Homebrew/Library/Taps/homebrew/homebrew-core
  - git checkout 25ffe1ce6fe Formula/qt.rb
  - cd $HOME
  - brew install qt5
  - chmod +x ./get-pyqt5-osx.sh
  - ./get-pyqt5-osx.sh

install:
  - pip install git+https://github.com/pyinstaller/pyinstaller.git
  - sudo pip install cffi
  - sudo pip install --upgrade setuptools

script:
  - pyinstaller --windowed browser.spec
  - ls dist/
  - ls dist/WebBrowser
  - ls dist/WebBrowser.app
  - ls dist/WebBrowser.app/Contents
  - ls dist/WebBrowser.app/Contents/Resources
  - ./dist/WebBrowser.app/Contents/MacOS/WebBrowser

before_deploy:
  - zip -r build-$TRAVIS_OS_NAME.zip dist/WebBrowser.app

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: $GH_TOKEN
  file:
    - build-$TRAVIS_OS_NAME.zip
  on:
    tags: true
