os: osx
language: generic
env: PYTHON=3.6
sudo: true

install:
  - pip3 install git+https://github.com/pyinstaller/pyinstaller.git
  - sudo pip3 install PyQt5 cffi

script:
  - pyinstaller --windowed browser.spec
  - brew install tree
  - tree dist/WebBrowser.app
  - ./dist/WebBrowser.app/Contents/MacOS/WebBrowser

before_deploy:
  - zip -r build-$TRAVIS_OS_NAME.zip dist/WebBrowser.app

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: $GH_TOKEN
  file:
    - build-$TRAVIS_OS_NAME.zip
  on:
    tags: true
