os: osx
language: generic
services:
  - xvfb
cache:
  pip: true
  directories:
    - $HOME/sip-4.19.13
    - $HOME/PyQt5_gpl-5.11.2
sudo: true


before_install:
  - pip install msgpack gevent enum34
  - brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/56c500b569c724b049be7ab9e12d9693f85522f9/Formula/qt.rb
  - chmod +x ./get-pyqt5-osx.sh
  - ./get-pyqt5-osx.sh
  - brew install tree
  - tree /usr/local/Cellar/qt/5.11.2

install:
  - sudo pip install pyinstaller
  - sudo pip install cffi
  - sudo pip install --upgrade setuptools

script:
  - pyinstaller --windowed browser.spec
  - cp -r ./dist/WebBrowser.app/Contents/Resources/PyQt5/Qt/lib/QtWebEngineCore.framework/Resources/* ./dist/WebBrowser.app/Contents/Resources
  - ls ./dist/WebBrowser.app/Contents/Resources
  - cp -r ./dist/WebBrowser.app/Contents/Resources/PyQt5/Qt/lib/QtWebEngineCore.framework/Resources/* ./dist/WebBrowser.app/Contents/MacOS
  - ls ./dist/WebBrowser.app/Contents/MacOS
  - mkdir -p ./dist/WebBrowser.app/Contents/MacOS/PyQt5/Qt/lib/QtWebEngineCore.framework/Versions/5
  - cp ./dist/WebBrowser.app/Contents/MacOS/QtWebEngineCore ./dist/WebBrowser.app/Contents/MacOS/PyQt5/Qt/lib/QtWebEngineCore.framework/Versions/5
  - ls ./dist/WebBrowser.app/Contents/MacOS/PyQt5/Qt/lib/QtWebEngineCore.framework/Versions/5
  - mkdir -p ./dist/WebBrowser.app/Contents/Resources/PyQt5/Qt/lib/QtWebEngineCore.framework/Versions/5
  - cp ./dist/WebBrowser.app/Contents/MacOS/QtWebEngineCore ./dist/WebBrowser.app/Contents/Resources/PyQt5/Qt/lib/QtWebEngineCore.framework/Versions/5
  - ls ./dist/WebBrowser.app/Contents/Resources/PyQt5/Qt/lib/QtWebEngineCore.framework/Versions/5
  - ./dist/WebBrowser.app/Contents/MacOS/WebBrowser

before_deploy:
  - zip -r build-$TRAVIS_OS_NAME.zip dist/WebBrowser.app

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: $GH_TOKEN
  file:
    - build-$TRAVIS_OS_NAME.zip
  on:
    tags: true
